/**
 * Static Gamification Catalogue
 *
 * Defines every badge and achievement available on NeyborHuud.
 * Used as a fallback when the backend gamification APIs are not yet live,
 * so users always see the full catalogue (earned items are overlaid by the API).
 */

import { Badge, Achievement } from "@/types/api";

// ─── BADGES ──────────────────────────────────────────────────────────────────
//
// Rarity tiers: common → uncommon → rare → epic → legendary
//
export const STATIC_BADGES: Badge[] = [
  // ── Onboarding ──
  {
    id: "badge_welcome",
    name: "Welcome NeyburH",
    icon: "👋",
    rarity: "common",
    description: "Joined NeyborHuud and completed your profile.",
  },
  {
    id: "badge_verified",
    name: "Verified Identity",
    icon: "✅",
    rarity: "common",
    description: "Verified your identity and location on NeyborHuud.",
  },
  // ── Feed / Content ──
  {
    id: "badge_first_post",
    name: "First Words",
    icon: "📝",
    rarity: "common",
    description: "Made your very first post in the community feed.",
  },
  {
    id: "badge_conversation",
    name: "Conversation Starter",
    icon: "🗣️",
    rarity: "common",
    description: "Received your first comment on a post.",
  },
  {
    id: "badge_prolific",
    name: "Prolific Poster",
    icon: "📣",
    rarity: "uncommon",
    description: "Published 25 posts in your community.",
  },
  {
    id: "badge_content_creator",
    name: "Content Creator",
    icon: "🎨",
    rarity: "rare",
    description: "Published 100 posts — a true voice of the Huud.",
  },
  // ── Social ──
  {
    id: "badge_good_neighbour",
    name: "Good NeyburH",
    icon: "🤝",
    rarity: "uncommon",
    description: "Helped 5 NeyburHs by responding to help requests.",
  },
  {
    id: "badge_community_pillar",
    name: "Community Pillar",
    icon: "🏛️",
    rarity: "rare",
    description: "Consistently active for 3 months straight in your community.",
  },
  {
    id: "badge_super_connector",
    name: "Super Connector",
    icon: "🔗",
    rarity: "epic",
    description: "Connected with 50 NeyburHs on NeyborHuud.",
  },
  {
    id: "badge_community_hero",
    name: "Community Hero",
    icon: "🦸",
    rarity: "epic",
    description: "Helped 20 NeyburHs — your community counts on you.",
  },
  // ── Marketplace ──
  {
    id: "badge_market_opener",
    name: "Market Opener",
    icon: "🛍️",
    rarity: "common",
    description: "Listed your first item on the marketplace.",
  },
  {
    id: "badge_first_sale",
    name: "First Sale",
    icon: "💰",
    rarity: "uncommon",
    description: "Completed your very first marketplace sale.",
  },
  {
    id: "badge_top_seller",
    name: "Top Seller",
    icon: "🏆",
    rarity: "epic",
    description: "Successfully completed 20 marketplace sales.",
  },
  // ── Jobs ──
  {
    id: "badge_job_creator",
    name: "Job Creator",
    icon: "💼",
    rarity: "uncommon",
    description: "Posted your first job listing in the community.",
  },
  {
    id: "badge_employer",
    name: "Local Employer",
    icon: "🏢",
    rarity: "rare",
    description: "Posted 5 job listings and hired from the community.",
  },
  // ── Events ──
  {
    id: "badge_event_host",
    name: "Event Host",
    icon: "🎉",
    rarity: "uncommon",
    description: "Organised your first community event.",
  },
  {
    id: "badge_event_legend",
    name: "Event Legend",
    icon: "🎪",
    rarity: "epic",
    description: "Attended or organised 10 community events.",
  },
  // ── Services ──
  {
    id: "badge_service_pro",
    name: "Service Pro",
    icon: "🔧",
    rarity: "uncommon",
    description: "Offered your first professional service on NeyborHuud.",
  },
  {
    id: "badge_trusted_pro",
    name: "Trusted Professional",
    icon: "⭐",
    rarity: "rare",
    description: "Maintained a 4.5+ rating across 10 service bookings.",
  },
  // ── Safety ──
  {
    id: "badge_safety_guardian",
    name: "Safety Guardian",
    icon: "🛡️",
    rarity: "rare",
    description: "Reported 3 safety concerns that were verified and acted on.",
  },
  {
    id: "badge_sos_responder",
    name: "SOS Responder",
    icon: "🚨",
    rarity: "rare",
    description: "Responded to a NeyburH's SOS distress alert.",
  },
  // ── Streaks / Gamification ──
  {
    id: "badge_streak_master",
    name: "Streak Master",
    icon: "🔥",
    rarity: "epic",
    description: "Maintained a 30-day consecutive daily check-in streak.",
  },
  {
    id: "badge_trusted_voice",
    name: "Trusted Voice",
    icon: "💎",
    rarity: "rare",
    description: "Reached a trust score of 75% or higher.",
  },
  {
    id: "badge_coins_collector",
    name: "HuudCoins Collector",
    icon: "🪙",
    rarity: "epic",
    description: "Accumulated 5,000 HuudCoins through community participation.",
  },
  // ── FYI Bulletins ──
  {
    id: "badge_bulletin_board",
    name: "Bulletin Board",
    icon: "📌",
    rarity: "common",
    description: "Shared your first FYI bulletin with the community.",
  },
  {
    id: "badge_public_announcer",
    name: "Public Announcer",
    icon: "📢",
    rarity: "uncommon",
    description: "Published 10 FYI bulletins that kept your Huud informed.",
  },
  // ── Gossip Locale ──
  {
    id: "badge_gossip_starter",
    name: "Gossip Starter",
    icon: "💬",
    rarity: "common",
    description: "Started your first community discussion in Gossip Locale.",
  },
  {
    id: "badge_social_influencer",
    name: "Social Influencer",
    icon: "🎤",
    rarity: "epic",
    description: "Your posts consistently generate the most engagement in the Huud.",
  },
  // ── Messages / Chat ──
  {
    id: "badge_first_message",
    name: "First Hello",
    icon: "✉️",
    rarity: "common",
    description: "Sent your first direct message to a NeyburH.",
  },
  {
    id: "badge_connector",
    name: "Always Online",
    icon: "📱",
    rarity: "uncommon",
    description: "Exchanged 100 messages with NeyburHs on the platform.",
  },
  // ── Local News ──
  {
    id: "badge_news_reader",
    name: "Informed Citizen",
    icon: "📰",
    rarity: "common",
    description: "Read your first local news article on NeyborHuud.",
  },
  {
    id: "badge_news_contributor",
    name: "Community Reporter",
    icon: "🗞️",
    rarity: "uncommon",
    description: "Contributed or upvoted 5 local news tips.",
  },
  // ── TrustOS — Trust Score Milestones ──
  {
    id: "badge_seedling",
    name: "Seedling",
    icon: "🌱",
    rarity: "common",
    description: "Email verified — you have taken your first step on NeyborHuud.",
  },
  {
    id: "badge_sapling",
    name: "Sapling",
    icon: "🌿",
    rarity: "uncommon",
    description: "Profile completed with photo, display name, and pinned home location.",
  },
  {
    id: "badge_tree",
    name: "Tree",
    icon: "🌳",
    rarity: "rare",
    description: "Community vouched — your NeyburHs trust you.",
  },
  {
    id: "badge_baobab",
    name: "Baobab",
    icon: "🌲",
    rarity: "epic",
    description: "Reached the highest trust level — a permanent pillar of the Huud.",
  },
  // ── TrustOS — Vouching ──
  {
    id: "badge_voucher",
    name: "Community Voucher",
    icon: "🤜",
    rarity: "uncommon",
    description: "Vouched for 3 NeyburHs — helping them build their trust profile.",
  },
  {
    id: "badge_trusted_neighbour",
    name: "Trusted NeyburH",
    icon: "🫱",
    rarity: "rare",
    description: "Received 5 community vouches from verified NeyburHs.",
  },
  // ── Referrals ──
  {
    id: "badge_ambassador",
    name: "NeyborHuud Ambassador",
    icon: "📣",
    rarity: "uncommon",
    description: "Referred 3 friends who successfully joined NeyborHuud.",
  },
  {
    id: "badge_recruiter",
    name: "Community Recruiter",
    icon: "🏘️",
    rarity: "rare",
    description: "Referred 10 active NeyburHs — your Huud is growing.",
  },
  // ── Engagement (Comments & Reactions) ──
  {
    id: "badge_first_comment",
    name: "Conversationalist",
    icon: "💭",
    rarity: "common",
    description: "Commented on your first post in the community feed.",
  },
  {
    id: "badge_liked",
    name: "Good Vibes",
    icon: "❤️",
    rarity: "common",
    description: "Liked 10 posts — spreading positivity in the Huud.",
  },
  // ── Level Milestones ──
  {
    id: "badge_level_5",
    name: "Rising NeyburH",
    icon: "⬆️",
    rarity: "uncommon",
    description: "Reached Level 5 on NeyborHuud.",
  },
  {
    id: "badge_level_10",
    name: "Huud Regular",
    icon: "🏅",
    rarity: "rare",
    description: "Reached Level 10 — a respected face in the Huud.",
  },
  {
    id: "badge_level_15",
    name: "Community Elder",
    icon: "🎖️",
    rarity: "epic",
    description: "Reached Level 15 — your wisdom shapes the Huud.",
  },
  // ── Guardian of the Ward (Safety + SOS) ──
  {
    id: "badge_guardian_ward",
    name: "Guardian of the Ward",
    icon: "⚔️",
    rarity: "epic",
    description: "Responded to and resolved a NeyburH's SOS emergency alert.",
  },
  // ── Legendary ──
  {
    id: "badge_og",
    name: "NeyborHuud OG",
    icon: "🌟",
    rarity: "legendary",
    description: "One of the first 1,000 members to join NeyborHuud.",
  },
  {
    id: "badge_legend",
    name: "Community Legend",
    icon: "👑",
    rarity: "legendary",
    description: "Reached Level 20 — a true pillar of the Huud.",
  },
  {
    id: "badge_platinum",
    name: "Platinum NeyburH",
    icon: "💜",
    rarity: "legendary",
    description: "Reached the Platinum subscription tier.",
  },
];

// ─── ACHIEVEMENTS ─────────────────────────────────────────────────────────────
//
// progress: 0 in the static catalogue — real values are supplied by the API.
//
export const STATIC_ACHIEVEMENTS: Achievement[] = [
  // ── Getting started ──
  {
    id: "ach_first_post",
    name: "First Steps",
    description: "Make your first post in the community feed.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 50 },
  },
  {
    id: "ach_5_posts",
    name: "Getting Started",
    description: "Post 5 times in the community feed.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 100 },
  },
  {
    id: "ach_25_posts",
    name: "Prolific Poster",
    description: "Post 25 times — your NeyburHs know your name.",
    progress: 0,
    goal: 25,
    completed: false,
    reward: { points: 250 },
  },
  {
    id: "ach_100_posts",
    name: "Content Machine",
    description: "Reach 100 posts in the community feed.",
    progress: 0,
    goal: 100,
    completed: false,
    reward: { points: 500 },
  },
  // ── Marketplace ──
  {
    id: "ach_first_listing",
    name: "Open for Business",
    description: "List your first item on the marketplace.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 75 },
  },
  {
    id: "ach_5_sales",
    name: "Marketplace Seller",
    description: "Complete 5 successful marketplace sales.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 200 },
  },
  {
    id: "ach_20_sales",
    name: "Power Seller",
    description: "Complete 20 marketplace sales.",
    progress: 0,
    goal: 20,
    completed: false,
    reward: { points: 500 },
  },
  // ── Events ──
  {
    id: "ach_attend_event",
    name: "Event Goer",
    description: "Attend your first community event.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 75 },
  },
  {
    id: "ach_5_events",
    name: "Event Enthusiast",
    description: "Attend or RSVP to 5 community events.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 150 },
  },
  {
    id: "ach_organise_events",
    name: "Event Organiser",
    description: "Organise 3 community events.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 300 },
  },
  // ── Helping NeyburHs ──
  {
    id: "ach_help_5",
    name: "Helpful NeyburH",
    description: "Help 5 NeyburHs by responding to help requests.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 200 },
  },
  {
    id: "ach_help_20",
    name: "Community Champion",
    description: "Help 20 NeyburHs — you are the backbone of the Huud.",
    progress: 0,
    goal: 20,
    completed: false,
    reward: { points: 500 },
  },
  // ── Jobs ──
  {
    id: "ach_post_jobs",
    name: "Job Creator",
    description: "Post 3 job listings in your community.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 150 },
  },
  // ── Services ──
  {
    id: "ach_offer_services",
    name: "Service Provider",
    description: "Offer 3 professional services on NeyborHuud.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 200 },
  },
  // ── Streaks ──
  {
    id: "ach_streak_7",
    name: "Weekly Warrior",
    description: "Check in for 7 consecutive days.",
    progress: 0,
    goal: 7,
    completed: false,
    reward: { points: 100 },
  },
  {
    id: "ach_streak_30",
    name: "Monthly Regular",
    description: "Check in every day for 30 days in a row.",
    progress: 0,
    goal: 30,
    completed: false,
    reward: { points: 500 },
  },
  {
    id: "ach_streak_100",
    name: "Century Streak",
    description: "Maintain a 100-day check-in streak.",
    progress: 0,
    goal: 100,
    completed: false,
    reward: { points: 1500 },
  },
  // ── Social ──
  {
    id: "ach_connect_10",
    name: "Social Butterfly",
    description: "Connect with 10 NeyburHs on NeyborHuud.",
    progress: 0,
    goal: 10,
    completed: false,
    reward: { points: 150 },
  },
  {
    id: "ach_connect_50",
    name: "Mega Connector",
    description: "Connect with 50 NeyburHs.",
    progress: 0,
    goal: 50,
    completed: false,
    reward: { points: 400 },
  },
  // ── Safety ──
  {
    id: "ach_safety",
    name: "Safety Champion",
    description: "Report 3 verified safety concerns in your community.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 200 },
  },
  // ── Coins ──
  {
    id: "ach_1000_coins",
    name: "Coin Collector",
    description: "Earn 1,000 HuudCoins through community participation.",
    progress: 0,
    goal: 1000,
    completed: false,
    reward: { points: 300 },
  },
  {
    id: "ach_5000_coins",
    name: "Coin Hoarder",
    description: "Accumulate 5,000 HuudCoins.",
    progress: 0,
    goal: 5000,
    completed: false,
    reward: { points: 750 },
  },
  // ── Profile & Onboarding ──
  {
    id: "ach_complete_profile",
    name: "Full Profile",
    description: "Complete your NeyborHuud profile (name, photo, bio, location).",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 100 },
  },
  {
    id: "ach_verify_identity",
    name: "Face of the Huud",
    description: "Complete your profile — add a photo, display name, and pin your home location.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 200 },
  },
  // ── FYI Bulletins ──
  {
    id: "ach_first_bulletin",
    name: "First Bulletin",
    description: "Share your first FYI bulletin with the community.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 75 },
  },
  {
    id: "ach_10_bulletins",
    name: "Information Hub",
    description: "Share 10 FYI bulletins that keep your Huud informed.",
    progress: 0,
    goal: 10,
    completed: false,
    reward: { points: 200 },
  },
  // ── Comments & Engagement ──
  {
    id: "ach_10_comments",
    name: "Active Commenter",
    description: "Comment on 10 posts in the community feed.",
    progress: 0,
    goal: 10,
    completed: false,
    reward: { points: 100 },
  },
  {
    id: "ach_50_reactions",
    name: "Good Vibes",
    description: "React to 50 posts or comments.",
    progress: 0,
    goal: 50,
    completed: false,
    reward: { points: 100 },
  },
  // ── Messages / Chat ──
  {
    id: "ach_first_message",
    name: "First Hello",
    description: "Send your first direct message to a NeyburH.",
    progress: 0,
    goal: 1,
    completed: false,
    reward: { points: 50 },
  },
  {
    id: "ach_100_messages",
    name: "Chatty NeyburH",
    description: "Exchange 100 direct messages with NeyburHs.",
    progress: 0,
    goal: 100,
    completed: false,
    reward: { points: 150 },
  },
  // ── TrustOS — Vouching ──
  {
    id: "ach_vouch_3",
    name: "Community Voucher",
    description: "Vouch for 3 NeyburHs in your community.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 150 },
  },
  {
    id: "ach_vouched_5",
    name: "Well Trusted",
    description: "Receive 5 vouches from verified community members.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 250 },
  },
  // ── Referrals ──
  {
    id: "ach_refer_3",
    name: "Recruit 3 NeyburHs",
    description: "Refer 3 friends who join and verify their accounts.",
    progress: 0,
    goal: 3,
    completed: false,
    reward: { points: 300 },
  },
  {
    id: "ach_refer_10",
    name: "Community Builder",
    description: "Refer 10 active NeyburHs to NeyborHuud.",
    progress: 0,
    goal: 10,
    completed: false,
    reward: { points: 750 },
  },
  // ── Level Milestones ──
  {
    id: "ach_level_5",
    name: "Rising NeyburH",
    description: "Reach Level 5 on NeyborHuud.",
    progress: 0,
    goal: 5,
    completed: false,
    reward: { points: 200 },
  },
  {
    id: "ach_level_10",
    name: "Huud Regular",
    description: "Reach Level 10 — a respected face in the Huud.",
    progress: 0,
    goal: 10,
    completed: false,
    reward: { points: 500 },
  },
  {
    id: "ach_level_20",
    name: "Community Legend",
    description: "Reach Level 20 — the pinnacle of community status.",
    progress: 0,
    goal: 20,
    completed: false,
    reward: { points: 1500 },
  },
];
